<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
        <div id="login-content">
          <div class="row">
              <div id="right-div" class="col-md-12">
                    <div class="logged_in col-lg-12">
                      <span class="simple_page_icon"></span>
                      <h4 class="simple_page">Kurzuskód: <?php echo $_GET['id'];?></h4>
                      <h5 id="available_courses"><a href="courses_available.php">< Vissza a kurzusokhoz</a></h5>
                    </div>
                    <div class="col-lg-10 col-md-offset-1">
                        <?php
                        $id = $_GET['id'];
                        $available = true;
                        require_once '../config.php';
                        $stid = oci_parse($conn, "SELECT * FROM KURZUSOK WHERE kurzuskod='$id'");
                        oci_execute($stid);

                        echo '<table id="datatable" class="table table-hover table-condensed table-responsive datatable table-bordered">';
                        //// -- COLUMN NAME
                        $nfields = oci_num_fields($stid);
                        echo '<tr><a href="#">';
                        for ($i = 1; $i<=$nfields; $i++){
                            $field = oci_field_name($stid, $i);
                            echo '<td>' . $field . '</td>';
                        }
                        echo '</a></tr>';

                        //// -- SQL QUERY #2
                        oci_execute($stid);
                        while ( $row = oci_fetch_array($stid, OCI_ASSOC + OCI_RETURN_NULLS)) {
                            if($row['LETSZAM'] == $row['MAXLETSZAM']){
                              $available = false;
                            }
                            echo '<tr>';
                            foreach ($row as $item) {
                                echo '<td>' . $item . '</td>';
                            }
                            echo '</tr>';
                        }
                        echo '</table>';
                        //// -- CLOSE CONN
                        oci_close($conn);


                        if($available){
                        ?>
                        <span class="simple_course_icon_plus"></span>
                        <h5 id="available_courses_single"><a href="course_add.php?id=<?php echo $id; ?>">Kurzus felvétele</a></h5>
                        <?php } else { ?>
                        <span class="simple_course_icon_x"></span>
                        <h5 id="available_courses_single">A kurzus sajnos megtelt.</h5>
                        <?php } ?>
                 </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>
  <script>

  function addRowHandlers() {
      var table = document.getElementById("datatable");
      var rows = table.getElementsByTagName("tr");
      for (i = 0; i < rows.length; i++) {
          var currentRow = table.rows[i];
          var createClickHandler =
              function(row)
              {
                  return function() {
                                          var cell = row.getElementsByTagName("td")[0];
                                          var id = cell.innerHTML;
                                          window.location.href = "course.php?id=" + id;
                                   };
              };

          currentRow.onclick = createClickHandler(currentRow);
      }
  }
  window.onload = addRowHandlers();
  </script>
</html>
