<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
        <div id="login-content">
          <div class="row">
              <div id="right-div" class="col-md-12">
                    <div class="logged_in col-lg-12">
                      <span class="simple_page_icon"></span>
                      <h4 class="simple_page">Kurzusaim</h4>
                        <span class="simple_page_icon_plus"></span>
                      <h5 id="available_courses"><a href="courses_available.php">Felvehető kurzusok listája</a></h5>
                        <span class="simple_page_icon_table"></span>
                      <h5 id="available_courses"><a href="timetable.php">Aktuális órarend</a></h5>
                    </div>
                    <div class="col-lg-10 col-md-offset-1">
                        <?php
                        require_once '../config.php';
                        $stid = oci_parse($conn, 'SELECT DISTINCT FELVETTKURZUSOK.KURZUSKOD, NEV, oktatoeha, nap, kezdido, vegido, kredit FROM FELVETTKURZUSOK, KURZUSOK WHERE FELVETTKURZUSOK.KURZUSKOD = KURZUSOK.KURZUSKOD');
                        oci_execute($stid);

                        echo '<table id="datatable" class="table table-hover table-condensed table-responsive datatable table-bordered">';
                        //// -- COLUMN NAME
                        $nfields = oci_num_fields($stid);
                        echo '<tr><a href="#">';
                        for ($i = 1; $i<=$nfields; $i++){
                            $field = oci_field_name($stid, $i);
                            echo '<td>' . $field . '</td>';
                        }
                        echo '</a></tr>';

                        //// -- SQL QUERY #2
                        oci_execute($stid);
                        while ( $row = oci_fetch_array($stid, OCI_ASSOC + OCI_RETURN_NULLS)) {
                            echo '<tr>';
                            foreach ($row as $item) {
                                echo '<td>' . $item . '</td>';
                            }
                            echo '</tr>';
                        }
                        echo '</table>';

                        //// -- CLOSE CONN
                        oci_close($conn);
                        ?>
                  </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>
  <script>
  </script>
</html>
