<!DOCTYPE html>
<html lang="en">
  <body>
    <?php
    ?>
    <div class="container">
        <div id="login-content">
          <div class="row">
              <div id="right-div" class="col-md-12">
                    <div class="logged_in col-lg-12">
                      <span id="succes"></span>
                      <h4 id="login_succes">Sikeres bejelentkezés</h4>
                      <h3 id="welcome_text">
                        Üdvözöllek az ETR rendszerében. Böngéssz, keresgélj a kurzusok között, jeletnezz vizsgákra, csekkold a pénzügyeidet, egyszóval élvezd, hogy nem a <a href="https://www.neptun.u-szeged.hu/"> NEPTUN </a> rendszerét használod. Have fun!
                      </h3>
                      <img id="login_img" src="../img/thumbs_up.png">
                    </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>
