<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
        <div id="login-content">
          <div class="row">
              <div id="right-div" class="col-md-12">
                    <div class="logged_in col-lg-12">
                      <span class="simple_page_icon"></span>
                      <h4 class="simple_page">Aktuális órarend</h4>
                      <span class="simple_page_icon_plus"></span>
                    <h5 id="available_courses"><a href="courses.php">Kurzusok</a></h5>
                    </div>
                    <div class="col-lg-10 col-md-offset-1">
                        <?php
                        require_once '../config.php';
                        $j = 0;
                        $days = array('hétfő', 'kedd', 'szerda', 'csütörtök', 'péntek');
                        while($j <= 4){
                                echo '<h5>';
                                echo $days[$j];
                                echo '</h5>';
                                $stid = oci_parse($conn, "SELECT DISTINCT kezdido, vegido, nev, oktatoeha, kredit FROM FELVETTKURZUSOK, KURZUSOK WHERE FELVETTKURZUSOK.KURZUSKOD = KURZUSOK.KURZUSKOD AND nap='$days[$j]' ORDER BY kezdido DESC");
                                oci_execute($stid);

                                echo '<table id="datatable" class="table table-hover table-condensed table-responsive datatable table-bordered">';
                                //// -- COLUMN NAME
                                $nfields = oci_num_fields($stid);
                                echo '<tr><a href="#">';
                                for ($i = 1; $i<=$nfields; $i++){
                                    $field = oci_field_name($stid, $i);
                                    echo '<td>' . $field . '</td>';
                                }
                                echo '</a></tr>';

                                //// -- SQL QUERY #2
                                oci_execute($stid);
                                while ( $row = oci_fetch_array($stid, OCI_ASSOC + OCI_RETURN_NULLS)) {
                                    echo '<tr>';
                                    foreach ($row as $item) {
                                        echo '<td>' . $item . '</td>';
                                    }
                                    echo '</tr>';
                                }
                                echo '</table>';
                                $j++;
                        }
                        ?>
                  </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>
  <script>
  </script>
</html>
